### ISSUE TITLE
SSR not working

### ISSUE THREAD

**Issue by hoang17** [StevenYuysy/vue-content-placeholder#6]
im using vue-content-placeholder with vue SSR and got this error:

```
2017-06-11T10:42:28.442Z - error: ReferenceError: document is not defined
    at addStyle (eval at <anonymous> (/node_modules/vue-content-placeholder/dist/vue-content-placeholder.min.js:130:1), <anonymous>:116:22)
    at addStylesToDom (eval at <anonymous> node_modules/vue-content-placeholder/dist/vue-content-placeholder.min.js:130:1), <anonymous>:100:20)

```

**Comment by StevenYuysy** [comment]
I will try to fix it, but it will take some time.

**Comment by StevenYuysy** [comment]
Thx @fritx , now this lib support SSR.
